services:
  database:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lionel
      MYSQL_DATABASE: mybank
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mybank-network  # Ajoutez cette ligne
  backend:
    build:
      context: ./BackEnd # Utilisation du dossier BackEnd comme contexte
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8000:80"
    networks:
      - mybank-network
    command: ["sh", "/usr/local/bin/start-symfony.sh"]
    volumes:
      - ./BackEnd/mybank-backend:/var/www/html
      - ./BackEnd/config/apache2.conf:/etc/apache2/apache2.conf
      - ./BackEnd/mybank-backend/var/log:/var/www/html/var/log
      - ./BackEnd/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
    stdin_open: true
    tty: true
  frontend:
    build:
      context: ./FrontEnd
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - mybank-network
    volumes:
      - ./FrontEnd/my-bank-frontend:/app/my-bank-frontend
    stdin_open: true
    tty: true

  phpmyadmin:

      image: phpmyadmin/phpmyadmin

      restart: always

      ports:

        - "8080:80"  # Accès à phpMyAdmin sur le port 8080

      environment:

        PMA_HOST: database

        PMA_USER: root

        PMA_PASSWORD: lionel
      networks:
        - mybank-network  # Ajoutez cette ligne
networks:
    mybank-network:
     driver: bridge



volumes:
  db_data: